spring:
  application:
    name: backend-services-motores-colombia
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/motorescolombia
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          batch_size: 30
        generate_statistics: false
        order_inserts: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always

hibernate:
  cache:
    use_second_level_cache: true
    region:
      factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
    provider_class: net.sf.ehcache.hibernate.EhCacheProvider


springdoc:
  swagger-ui:
    path: /swagger-ui.html